routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('threads/create', 'Threads\ThreadsController@create')->name('threads.create');
Route::get('threads', 'Threads\ThreadsController@index')->name('threads.index');
Route::get('threads/{channel}', 'Threads\ThreadsController@index');
Route::get('threads/{channel}/{thread}', 'Threads\ThreadsController@show')->name('threads.show');
Route::delete('threads/{channel}/{thread}', 'Threads\ThreadsController@destroy')->name('threads.destroy');
Route::post('threads', 'Threads\ThreadsController@store')->name('threads.store');

Route::prefix('threads/{channel}/{thread}')->group(function () {
    Route::post('replies', 'Replies\RepliesController@store');
});
Route::delete('replies/{reply}', 'Replies\RepliesController@destroy');
Route::patch('replies/{reply}', 'Replies\RepliesController@update');

Route::post('replies/{reply}/favourites', 'Favourites\FavouritesController@store');
Route::delete('replies/{reply}/favourites', 'Favourites\FavouritesController@destroy');

Route::get('/profiles/{user}', 'Profiles\ProfilesController@show');

app/Models/Threads/Thread.php
<?php

namespace App\Models\Threads;

use App\Models\Activities\Activity;
use App\Models\Activities\RecordsActivity;
use App\Models\Channels\Channel;
use App\Models\Replies\Reply;
use App\Models\Users\User;
use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    use RecordsActivity;

    protected $guarded =[];

    protected $with = ['creator', 'channel'];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('replyCount', function ($builder) {
            $builder->withCount('replies');
        });


        static::deleting(function($thread){
            $thread->replies->each->delete();
        });
    }

    public function path()
    {
        return "/threads/{$this->channel->slug}/{$this->id}";
    }

    public function replies()
    {
        return $this->hasMany(Reply::class, 'thread_id');
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function addReply($reply)
    {
        $this->replies()->create($reply);
    }

    public function channel()
    {
        return $this->belongsTo(Channel::class, 'channel_id');
    }
    
    public function scopeFilter($query, $filters)
    {
        return $filters->apply($query);
    }

}

app/Http/Controllers/Threads/ThreadsController.php
<?php

namespace App\Http\Controllers\Threads;

use App\Filters\Threads\ThreadFilters;
use App\Models\Channels\Channel;
use App\Models\Threads\Thread;
use App\Models\Users\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ThreadsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }

    public function index(Channel $channel, ThreadFilters $filters)
    {
        $threads = Thread::latest()->filter($filters);
        if ($channel->exists)  {
            $threads = $channel->threads()->latest();
        }

        $threads = $threads->get();

        if(request()->wantsJson()) {
            return $threads;
        }

        return view('threads.index', compact('threads'));
    }


    public function create()
    {
        return view('threads.create');
    }

    public function store(Request $request)
    {
        $this->validate(request(),['title' => 'required', 'body' => 'required', 'channel_id' => 'required|exists:channels,id']);

        $thread = Thread::create([
            'user_id' => auth()->id(),
            'channel_id' => request('channel_id'),
            'title' => request('title'),
            'body' => request('body')
        ]);

        return redirect($thread->path())
            ->with('flash', 'Your thread was successfully published');
    }


    public function show($channelID, Thread $thread)
    {
        $replies = $thread->replies()->paginate(10);
        return view('threads.show', compact('thread', 'replies'));
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    public function destroy($channel, Thread $thread)
    {
        $this->authorize('update', $thread);


        $thread->delete();

        if(request()->wantsJson()) {
            return response([], 204);
        }

        return redirect("/threads");

    }
}

resources/views/threads/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create Thread</div>

                    <div class="card-body">
                        <form action="{{ route('threads.store') }}" method="POST">
                            @include('threads._partials.forms.thread')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/threads/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="text-uppercase font-weight-bold text-secondary">
                <h3>Forum Threads</h3>
            </div>
            @forelse($threads as $thread)
                <div class="card mt-3">
                    <div class="card-body">
                        <article>
                            <div class="level">
                                <h4 class="flex">
                                    <a href="/profiles/{{$thread->creator->name}}">{{ $thread->creator->name }}</a> posted:
                                    <a href="{{ $thread->path() }}">{{ $thread->title }}</a>
                                </h4>
                                <a href="{{ $thread->path() }}">
                                    {{ $thread->replies_count }} {{ str_plural('reply', $thread->replies_count) }}
                                </a>
                            </div>
                            <div class="body">{{ $thread->body }}</div>
                        </article>
                    </div>
                </div>
            @empty
                @component('common.empty-component')
                    @slot('message')
                        {{ __('No Threads yet') }}
                    @endslot
                @endcomponent
            @endforelse
        </div>
    </div>
@endsection

resources/views/threads/replies.blade.php
<reply :attributes="{{ $reply }}" inline-template v-cloak>
    <div id="reply-{{$reply->id}}" class="card my-2">
        <div class="card-header">
            <div class="level">
                <h5 class="flex">
                    <a href="/profiles/{{$reply->owner->name}}">{{ $reply->owner->name }}</a> said {{ $reply->created_at->diffForHumans() }}..
                </h5>
                <div>
                    <favourite :reply="{{ $reply }}"></favourite>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div v-if="editing">
                <div class="form-group">
                    <textarea  class="form-control" v-model="body"></textarea>
                   <div class="mt-2">
                       <button class="btn btn-success btn-sm" @click="update()">Update</button>
                       <button class="btn btn-secondary btn-sm" @click="editing=false">Cancel</button>
                   </div>
                </div>
            </div>
            <div v-else v-text="body"></div>
        </div>
        @can('update', $reply)
            <div class="card-footer level" v-if="editing==false">
                <span class="mr-2">
                    <button class="btn btn-sm btn-outline-primary" @click="editing = true">{{ __('Edit') }}</button>
                </span>
                <span>
                    <button class="btn btn-sm btn-outline-danger" @click="destroy()">{{ __('Delete') }}</button>
                </span>
            </div>
        @endcan
    </div>
</reply>

resources/views/threads/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <div class="level">
                            <span class="flex">
                                <h4 class="text-secondary font-weight-bold">
                                    <a href="/profiles/{{$thread->creator->name}}">{{ $thread->creator->name }}</a> posted: {{ $thread->title }}
                                </h4>
                            </span>
                        <span>
                                @can('update', $thread)
                                <form action="{{$thread->path()}}" method="POST">
                                        {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button class="btn btn-link text-danger">{{ __('Delete Thread') }}</button>
                                    </form>
                            @endcan
                            </span>
                    </div>
                </div>
                <div class="card-body">
                    <article>
                        <div class="body">
                            {{ $thread->body }}
                        </div>
                    </article>
                    <div class="card mt-4">
                        <div class="card-header"><h5 class="text-secondary font-weight-bold">Replies</h5></div>
                        <div class="card-body">
                            @forelse($replies as $reply)
                                @include('threads.replies')
                            @empty
                                @component('common.empty-component')
                                    @slot('message')
                                        {{ __('No Replies yet') }}
                                    @endslot
                                @endcomponent
                            @endforelse
                            {{$replies->links()}}
                        </div>
                    </div>
                </div>
            </div>

            <div class="card mt-3">
                <div class="card-body">
                    @if(auth()->check())
                        <form action="{{$thread->path().'/replies'}}" method="POST">
                            {{csrf_field()}}
                            <div class="form-group">
                                <textarea class="form-control {{ $errors->has('body') ? ' is-invalid' : '' }}" name="body" rows="2" placeholder="Have something to say..."></textarea>
                                @if ($errors->has('body'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('body') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group text-center">
                                <button class="btn btn-success" type="submit">Post</button>
                            </div>
                        </form>
                    @else
                        <div class="text-center">
                            <p class="lead">Please <a href="{{ route('login') }}">SingIn</a> in to participate in the discussion</p>
                        </div>
                    @endif

                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    This thread was published {{ $thread->created_at->diffForHumans() }} by <a href="/profiles/{{$thread->creator->name}}">{{ $thread->creator->name }}</a>,
                    and currently has {{ $thread->replies_count }} {{ str_plural('comment', $thread->replies_count) }}.

                </div>
            </div>
        </div>
    </div>
@endsection